# Generated by Django 2.1.2 on 2018-10-02 19:27

import django.core.validators
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpinqUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(code='inválido', message='Ingresa un nombre válido. Solo letras en minúscula y guiones bajos', regex='[a-z_]+')])),
                ('bio', models.TextField(blank=True, null=True)),
                ('pic', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='users/pics')),
                ('puntos', models.IntegerField(default=0, help_text='Puntaje del usuario (se le da por opinar)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
